#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# make stub C source for exporting TVP's internal functions.
#
# Python port of common/base/makestub.pl (Perl + Compress::Zlib + Digest::MD5).
# Byte-exact replacement: reproduces FuncStubs.{h,cpp} and tp_stub/tp_stub.{h,cpp}
# identically to the Perl original.
#
# Files are read/written as latin-1 with newline='' so every byte (incl. UTF-8
# Japanese comment bytes and any CR) is preserved verbatim, mirroring Perl's
# byteswise slurp/print with no PerlIO translation.
#
# usage: python gen_tpstub.py [core_base_dir]
#   core_base_dir defaults to two levels up from this script (i.e. src/core when
#   the script lives in common/base). Outputs (written only when the bytes
#   change; byte-identical to the former makestub.pl):
#     {core}/common/base/FuncStubs.h
#     {core}/common/base/FuncStubs.cpp
#     {core}/tp_stub/tp_stub.h
#     {core}/tp_stub/tp_stub.cpp
#
# After regenerating {core}/tp_stub/tp_stub.{h,cpp}, copy them into the
# plugins' tp_stub submodule as before (see README / tp_stub notes).

import os
import re
import sys
import zlib
import hashlib

FLAGS = re.DOTALL | re.ASCII

copyright = (
    "/*\n"
    "\n"
    "\tTVP2 ( T Visual Presenter 2 )  A script authoring tool\n"
    "\tCopyright (C) 2000-2009 W.Dee <dee@kikyou.info> and contributors\n"
    "\n"
    "\tSee details of license at \"license.txt\"\n"
    "*/\n"
    "/* This file is always generated by makestub.pl . */\n"
    "/* Modification by hand will be lost. */\n"
)

# --- global accumulators (mirror the Perl globals) -------------------------
num = 0
func_list = []      # @func_list
method_list = []    # @method_list
h_stub = []         # @h_stub
defs = ''           # $defs
impls = ''          # $impls

# per-run output buffers (we accumulate strings then write once)
OFH = []            # FuncStubs.~cpp   (list of strings)
OHFH = []           # tp_stub.h
OCFH = []           # tp_stub.cpp


def _strip(s):
    # Perl: s/^\s*(.*?)\s*$/$1/  (no /s, no /m)
    return re.sub(r'^\s*(.*?)\s*$', r'\1', s, count=1, flags=re.ASCII)


def normalize_string(s):
    # Perl:
    #   s/^\s*(.*?)\s*$/$1/           (strip; subsumed by the tokenize below)
    #   s/\*\*/\* \*/g  (twice)       (** -> * *)
    #   @a = split(/\s|\b/, $s); keep non-empty non-ws; join ' '
    # The kept tokens of split(/\s|\b/) are exactly the maximal runs of word
    # chars OR of non-word/non-space chars, so findall reproduces them.
    s = re.sub(r'\*\*', '* *', s)
    s = re.sub(r'\*\*', '* *', s)
    tokens = re.findall(r'\w+|[^\w\s]+', s, flags=re.ASCII)
    return ' '.join(tokens)


def _perl_split_re(pattern, s):
    # Perl split(/pattern/, $s): '' -> (); trailing empty fields removed.
    # (Our pattern \s*,\s* always requires a comma, so no zero-width concerns.)
    if s == '':
        return []
    parts = re.split(pattern, s)
    while parts and parts[-1] == '':
        parts.pop()
    return parts


def _perl_split_comma(s):
    # Perl split(/,/, $s): '' -> (); trailing empty fields removed (LIMIT=0).
    if s == '':
        return []
    parts = s.split(',')
    while parts and parts[-1] == '':
        parts.pop()
    return parts


def get_arg_names(args):
    out = ''
    for arg in _perl_split_comma(args):
        arg = _strip(arg)
        m = re.match(r'^(.*)=(.*)$', arg, flags=re.ASCII)  # drop default value
        if m:
            arg = m.group(1)
        arg = _strip(arg)
        # Perl: $arg =~ /(\w+)$/  -- on failure $1 keeps the value set by the
        # immediately-preceding successful match (the _strip above => arg).
        mm = re.search(r'(\w+)$', arg, flags=re.ASCII)
        piece = mm.group(1) if mm else arg
        if out != '':
            out += ', '
        out += piece
    return out


def except_arg_names(args):
    out = ''
    for arg in _perl_split_comma(args):
        arg = _strip(arg)
        m = re.match(r'^(.*)=(.*)$', arg, flags=re.ASCII)
        if m:
            arg = m.group(1)
        arg = _strip(arg)
        arg = re.sub(r'(.*?)(\w+)$', r'\1', arg, count=1, flags=re.ASCII)  # drop trailing name
        arg = _strip(arg)  # $1 becomes the stripped type; Perl uses $1 here
        if out != '':
            out += ','
        out += normalize_string(arg)
    return out


def get_ret_type(type_, prefix):
    if type_ == prefix + "_METHOD_RET_EMPTY":
        return 'void'
    m = re.search(re.escape(prefix) + r'_METHOD_RET\((.*?)\)', type_, flags=FLAGS)
    if m:
        return normalize_string(m.group(1))
    return normalize_string(type_)


def make_func_stub(rettype, name, arg, type_, prefix, isconst, isstatic, envname=None):
    global num
    rettype = rettype.replace('\n', ' ').replace('\t', ' ')
    name = name.replace('\n', ' ').replace('\t', ' ')
    arg = arg.replace('\n', ' ').replace('\t', ' ')

    is_ret_macro = rettype.startswith(prefix + "_METHOD_RET")

    func_exp_name = (
        ('' if is_ret_macro else normalize_string(rettype) + ' ') +
        type_ + '::' + normalize_string(name) + '(' + except_arg_names(arg) + ')' +
        (' const' if isconst else '')
    )

    md5 = hashlib.md5(func_exp_name.encode('latin-1')).hexdigest()

    mangled = "TVP_Stub_" + md5 + "\t"
    mangled += func_exp_name
    mangled += ("\t" + get_ret_type(rettype, prefix) +
                "(STDCALL *  __TVP_Stub_" + md5 + ")(" + type_ + " *_this" +
                (', ' if arg != '' else '') + normalize_string(arg) + ")")
    mangled += ("\t" + ('' if is_ret_macro else normalize_string(rettype)) +
                " " + normalize_string(type_) + "::" + normalize_string(name) +
                "(" + normalize_string(arg) + ")")
    mangled += "\tTVP_Stub_" + md5
    mangled += "\t" + md5
    mangled += "\t" + get_arg_names(arg)
    functype = (get_ret_type(rettype, prefix) +
                "(STDCALL * __functype)(" + ("const " if isconst else "") +
                ('' if isstatic else (type_ + " *" + (', ' if arg != '' else ''))) +
                normalize_string(except_arg_names(arg)) + ")")
    mangled += "\t" + functype
    if envname:
        mangled += "\t" + envname

    noreturn = 0
    if rettype == prefix + "_METHOD_RET_EMPTY":
        noreturn = 1
    elif re.search(re.escape(prefix) + r'_METHOD_RET\((.*?)\)', rettype, flags=FLAGS):
        noreturn = 2

    rettype = get_ret_type(rettype, prefix)

    if envname:
        OFH.append("#ifdef " + envname + "\n")

    OFH.append("static ")
    OFH.append(normalize_string(rettype))
    OFH.append(" STDCALL ")
    OFH.append("TVP_Stub_" + md5)
    if isstatic:
        OFH.append("(")
    else:
        OFH.append("(" + type_ + " * _this")
        if arg != '':
            OFH.append(", ")

    OFH.append(normalize_string(arg))
    OFH.append(")\n")
    OFH.append("{\n")
    argnames = get_arg_names(arg)
    if name == type_:
        # constructor
        OFH.append("\t::new (_this) " + name + "(" + argnames + ");\n")
        h = ("\t" + normalize_string(name) + "(" + normalize_string(arg) + ")\n" +
             "\t{\n" +
             "\t\tif(!TVPImportFuncPtr" + md5 + ")\n" +
             "\t\t{\n" +
             "\t\t\tstatic char funcname[] = \"" + func_exp_name + "\";\n" +
             "\t\t\tTVPImportFuncPtr" + md5 + " = TVPGetImportFuncPtr(funcname);\n" +
             "\t\t}\n" +
             "\t\ttypedef " + functype + ";\n" +
             "\t\t((__functype)(TVPImportFuncPtr" + md5 + "))(" +
             ('' if isstatic else ("this" + (', ' if argnames != '' else ''))) + argnames + ");\n" +
             "\t}\n")
    elif name == "~" + type_:
        # destructor
        OFH.append("\t_this->" + name + "(" + argnames + ");\n")
        h = ("\t" + normalize_string(name) + "(" + normalize_string(arg) + ")\n" +
             "\t{\n" +
             "\t\tif(!TVPImportFuncPtr" + md5 + ")\n" +
             "\t\t{\n" +
             "\t\t\tstatic char funcname[] = \"" + func_exp_name + "\";\n" +
             "\t\t\tTVPImportFuncPtr" + md5 + " = TVPGetImportFuncPtr(funcname);\n" +
             "\t\t}\n" +
             "\t\ttypedef " + functype + ";\n" +
             "\t\t((__functype)(TVPImportFuncPtr" + md5 + "))(" +
             ('' if isstatic else ("this" + (', ' if argnames != '' else ''))) + argnames + ");\n" +
             "\t}\n")
    else:
        OFH.append("\t")
        OFH.append("return ")
        if isstatic:
            OFH.append(type_ + "::" + name + "(" + argnames + ");\n")
        else:
            OFH.append("_this->" + name + "(" + argnames + ");\n")
        h = ("\t" + ('static ' if isstatic else '') + ('' if noreturn else rettype + ' ') +
             normalize_string(name) + "(" + normalize_string(arg) + ")" +
             (' const' if isconst else '') + "\n" +
             "\t{\n" +
             "\t\tif(!TVPImportFuncPtr" + md5 + ")\n" +
             "\t\t{\n" +
             "\t\t\tstatic char funcname[] = \"" + func_exp_name + "\";\n" +
             "\t\t\tTVPImportFuncPtr" + md5 + " = TVPGetImportFuncPtr(funcname);\n" +
             "\t\t}\n" +
             "\t\ttypedef " + functype + ";\n" +
             "\t\t" + ('' if rettype == 'void' else 'return ') +
             "((__functype)(TVPImportFuncPtr" + md5 + "))(" +
             ('' if isstatic else ("this" + (', ' if argnames != '' else ''))) + argnames + ");\n" +
             "\t}\n")
    OFH.append("}\n")

    if envname:
        OFH.append("#else\n")
        OFH.append("static void STDCALL TVP_Stub_" + md5 + "(){}\n")
        OFH.append("#endif // " + envname + "\n")

    if envname:
        h = "#ifdef " + envname + "\n" + h + "#endif // " + envname + "\n"

    func_list.append(mangled)
    h_stub.append(h)
    num += 1


def list_func_stub(prefix, content, type_):
    p = re.escape(prefix)
    grp3 = r'\(\s*(.*?)\s*,\s*(.*?)\s*,\s*\((.*?)\)\s*\)'
    grp4 = r'\(\s*(.*?)\s*,\s*(.*?)\s*,\s*(.*?)\s*,\s*\((.*?)\)\s*\)'

    for m in re.finditer(p + r'_METHOD_DEF' + grp3, content, flags=FLAGS):
        make_func_stub(m.group(1), m.group(2), m.group(3), type_, prefix, 0, 0)
    for m in re.finditer(p + r'_CONST_METHOD_DEF' + grp3, content, flags=FLAGS):
        make_func_stub(m.group(1), m.group(2), m.group(3), type_, prefix, 1, 0)
    for m in re.finditer(p + r'_STATIC_METHOD_DEF' + grp3, content, flags=FLAGS):
        make_func_stub(m.group(1), m.group(2), m.group(3), type_, prefix, 0, 1)
    for m in re.finditer(p + r'_STATIC_CONST_METHOD_DEF' + grp3, content, flags=FLAGS):
        make_func_stub(m.group(1), m.group(2), m.group(3), type_, prefix, 1, 1)

    for m in re.finditer(p + r'_METHOD_DEF_ENV' + grp4, content, flags=FLAGS):
        make_func_stub(m.group(2), m.group(3), m.group(4), type_, prefix, 0, 0, m.group(1))
    for m in re.finditer(p + r'_CONST_METHOD_DEF_ENV' + grp4, content, flags=FLAGS):
        make_func_stub(m.group(2), m.group(3), m.group(4), type_, prefix, 1, 0, m.group(1))
    for m in re.finditer(p + r'_STATIC_METHOD_DEF_ENV' + grp4, content, flags=FLAGS):
        make_func_stub(m.group(2), m.group(3), m.group(4), type_, prefix, 0, 1, m.group(1))
    for m in re.finditer(p + r'_STATIC_CONST_METHOD_DEF_ENV' + grp4, content, flags=FLAGS):
        make_func_stub(m.group(2), m.group(3), m.group(4), type_, prefix, 1, 1, m.group(1))


def make_exp_stub(rettype, name, arg, envname=None):
    global num
    rettype = rettype.replace('\n', ' ').replace('\t', ' ')
    name = name.replace('\n', ' ').replace('\t', ' ')
    arg = arg.replace('\n', ' ').replace('\t', ' ')

    func_exp_name = (normalize_string(rettype) + ' ' +
                     '::' + normalize_string(name) + '(' + except_arg_names(arg) + ')')

    md5 = hashlib.md5(func_exp_name.encode('latin-1')).hexdigest()

    mangled = "TVP_Stub_" + md5 + "\t" + func_exp_name
    mangled += ("\t" + normalize_string(rettype) +
                " (STDCALL *" + normalize_string(name) + ")(" + normalize_string(arg) + ")")
    mangled += ("\t" + normalize_string(rettype) + " " + normalize_string(name) +
                "(" + normalize_string(arg) + ")")
    mangled += "\t" + name
    mangled += "\t" + md5
    mangled += "\t" + get_arg_names(arg)
    mangled += ("\t" + normalize_string(rettype) +
                " (STDCALL * __functype)(" + normalize_string(except_arg_names(arg)) + ")")
    mangled += "\t" + normalize_string(rettype)
    if envname:
        mangled += "\t" + envname

    if envname:
        OFH.append("#ifdef " + envname + "\n")

    OFH.append("static ")
    OFH.append(normalize_string(rettype))
    OFH.append(" STDCALL ")
    OFH.append("TVP_Stub_" + md5 + "(")
    OFH.append(normalize_string(arg))
    OFH.append(")\n")
    OFH.append("{\n")
    argnames = get_arg_names(arg)
    OFH.append("\t")
    OFH.append("return ")
    OFH.append(name + "(" + argnames + ");\n")
    OFH.append("}\n")

    if envname:
        OFH.append("#else\n")
        OFH.append("static void STDCALL TVP_Stub_" + md5 + "(){}\n")
        OFH.append("#endif // " + envname + "\n")

    func_list.append(mangled)
    num += 1


def process_exp_stub(path):
    global defs, impls
    content = read_file(path)

    for m in re.finditer(r'/\*\[\*/(.*?)/\*\]\*/', content, flags=FLAGS):
        defs += m.group(1) + "\n"

    for m in re.finditer(r'/\*\[C\*/(.*?)/\*C\]\*/', content, flags=FLAGS):
        impls += m.group(1) + "\n"

    for m in re.finditer(r'TJS_EXP_FUNC_DEF_ENV\(\s*(.*?)\s*,\s*(.*?)\s*,\s*(.*?)\s*,\s*\((.*?)\)\s*\)',
                         content, flags=FLAGS):
        make_exp_stub(m.group(2), m.group(3), m.group(4), m.group(1))

    for m in re.finditer(r'TJS_EXP_FUNC_DEF\(\s*(.*?)\s*,\s*(.*?)\s*,\s*\((.*?)\)\s*\)',
                         content, flags=FLAGS):
        make_exp_stub(m.group(1), m.group(2), m.group(3))

    for m in re.finditer(r'TVP_GL_FUNC_PTR_EXTERN_DECL\(\s*(.*?)\s*,\s*(.*?)\s*,\s*\((.*?)\)\s*\)',
                         content, flags=FLAGS):
        make_exp_stub(m.group(1), m.group(2), m.group(3))


# --- file IO (latin-1, byte-preserving) ------------------------------------
CORE = None  # set in main


def read_file(rel):
    path = rel if os.path.isabs(rel) else os.path.join(CORE, rel)
    with open(path, 'r', encoding='latin-1', newline='') as f:
        return f.read()


def write_file(rel, text):
    # copy-if-differ: only rewrite when the bytes change, so unchanged outputs
    # keep their mtime and don't trigger a needless rebuild (this replaces the
    # old copy_if_differ.pl + FuncStubs.~cpp/~h tilde-temp dance).
    path = rel if os.path.isabs(rel) else os.path.join(CORE, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    data = text.encode('latin-1')
    try:
        with open(path, 'rb') as f:
            if f.read() == data:
                print("unchanged " + rel)
                return
    except FileNotFoundError:
        pass
    with open(path, 'wb') as f:
        f.write(data)
    print("wrote     " + rel)


def main():
    global CORE, func_list, method_list, h_stub, defs, impls, num
    global variant, variantoctet, string, variantstring
    global defs_system, defs_misc

    script_dir = os.path.dirname(os.path.abspath(__file__))
    if len(sys.argv) > 1:
        CORE = os.path.abspath(sys.argv[1])
    else:
        # script assumed at {core}/common/base
        CORE = os.path.abspath(os.path.join(script_dir, '..', '..'))

    # ---- FuncStubs.~h : just copyright + extern decl -----------------------
    fh_h = []
    fh_h.append(copyright)
    fh_h.append("\n"
                "extern void TVPExportFunctions();\n"
                "\n")

    # ---- FuncStubs.~cpp : copyright + includes -----------------------------
    OFH.append(copyright)
    OFH.append("\n"
               "\n"
               "#include \"tjsCommHead.h\"\n"
               "\n"
               "#include \"tjsVariant.h\"\n"
               "#include \"tjsString.h\"\n"
               "#include \"PluginImpl.h\"\n"
               "\n")

    # ---- class method stubs (tTJSVariant / Octet / String / VariantString) --
    content = read_file("common/tjs2/tjsVariant.h")
    m = re.search(r'/\*start-of-tTJSVariant\*/(.*?)/\*end-of-tTJSVariant\*/', content, flags=FLAGS)
    h_stub.clear()
    list_func_stub("TJS", m.group(1), "tTJSVariant")
    variant = list(h_stub)

    m = re.search(r'/\*start-of-tTJSVariantOctet\*/(.*?)/\*end-of-tTJSVariantOctet\*/', content, flags=FLAGS)
    h_stub.clear()
    list_func_stub("TJS", m.group(1), "tTJSVariantOctet")
    variantoctet = list(h_stub)

    content = read_file("common/tjs2/tjsString.h")
    m = re.search(r'/\*start-of-tTJSString\*/(.*?)/\*end-of-tTJSString\*/', content, flags=FLAGS)
    h_stub.clear()
    list_func_stub("TJS", m.group(1), "tTJSString")
    string = list(h_stub)

    content = read_file("common/tjs2/tjsVariantString.h")
    m = re.search(r'/\*start-of-tTJSVariantString\*/(.*?)/\*end-of-tTJSVariantString\*/', content, flags=FLAGS)
    h_stub.clear()
    list_func_stub("TJS", m.group(1), "tTJSVariantString")
    variantstring = list(h_stub)

    defs = ''
    impls = ''

    # snapshot method_list, reset func_list for exp stubs
    method_list = list(func_list)
    func_list.clear()

    # ---- process_exp_stub over the header list -----------------------------
    exp_headers = [
        ("tjsTypes.h",              "common/tjs2/tjsTypes.h",              None),
        ("tjsConfig.h",             "common/tjs2/tjsConfig.h",             None),
        ("tjsVariantString.h",      "common/tjs2/tjsVariantString.h",      None),
        ("tjsUtils.h",              "common/tjs2/tjsUtils.h",              None),
        ("tjsString.h",             "common/tjs2/tjsString.h",             None),
        ("tjsInterface.h",          "common/tjs2/tjsInterface.h",          None),
        ("tjsErrorDefs.h",          "common/tjs2/tjsErrorDefs.h",          None),
        ("tjsNative.h",             "common/tjs2/tjsNative.h",             None),
        ("tjsVariant.h",            "common/tjs2/tjsVariant.h",            None),
        ("tjsArray.h",              "common/tjs2/tjsArray.h",              None),
        ("tjsDictionary.h",         "common/tjs2/tjsDictionary.h",         None),
        ("tjs.h",                   "common/tjs2/tjs.h",                   None),
        ("tjsMessage.h",            "common/tjs2/tjsMessage.h",            None),
        ("tjsGlobalStringMap.h",    "common/tjs2/tjsGlobalStringMap.h",    None),
        ("tjsObject.h",             "common/tjs2/tjsObject.h",             None),
    ]
    for inc, path, _ in exp_headers:
        OFH.append("#include \"" + inc + "\"\n")
        process_exp_stub(path)
    # tjsObject.cpp additionally
    process_exp_stub("common/tjs2/tjsObject.cpp")

    defs_system = defs
    defs = ''

    OFH.append("#include \"StorageIntf.h\"\n"); process_exp_stub("common/base/StorageIntf.h")
    OFH.append("#include \"TextStream.h\"\n"); process_exp_stub("common/base/TextStream.h")
    OFH.append("#include \"CharacterSet.h\"\n"); process_exp_stub("common/base/CharacterSet.h")
    OFH.append("#include \"XP3Archive.h\"\n"); process_exp_stub("common/base/XP3Archive.h")
    OFH.append("#include \"EventIntf.h\"\n"); process_exp_stub("common/base/EventIntf.h")
    OFH.append("#include \"SystemIntf.h\"\n"); process_exp_stub("common/base/SystemIntf.h")
    OFH.append("#include \"SystemImpl.h\"\n"); process_exp_stub("win32/base/SystemImpl.h")
    OFH.append("#include \"ScriptMgnIntf.h\"\n"); process_exp_stub("common/base/ScriptMgnIntf.h")
    OFH.append("#include \"BinaryStream.h\"\n"); process_exp_stub("common/base/BinaryStream.h")
    OFH.append("#include \"StorageImpl.h\"\n"); process_exp_stub("win32/base/StorageImpl.h")
    OFH.append("#include \"PluginImpl.h\"\n"); process_exp_stub("win32/base/PluginImpl.h")
    OFH.append("#include \"SysInitIntf.h\"\n"); process_exp_stub("common/base/SysInitIntf.h")
    OFH.append("#include \"LicenseIntf.h\"\n"); process_exp_stub("common/base/LicenseIntf.h")
    OFH.append("#include \"SysInitImpl.h\"\n"); process_exp_stub("win32/base/SysInitImpl.h")
    OFH.append("#ifdef __WINVER__\n")
    OFH.append("#include \"DetectCPU.h\"\n")
    OFH.append("#endif\n")
    process_exp_stub("win32/environ/DetectCPU.h")
    OFH.append("#include \"ThreadIntf.h\"\n"); process_exp_stub("common/utils/ThreadIntf.h")
    OFH.append("#include \"DebugIntf.h\"\n"); process_exp_stub("common/utils/DebugIntf.h")
    OFH.append("#include \"Random.h\"\n"); process_exp_stub("common/utils/Random.h")
    OFH.append("#include \"ClipboardIntf.h\"\n"); process_exp_stub("common/utils/ClipboardIntf.h")
    OFH.append("#include \"TickCount.h\"\n"); process_exp_stub("common/utils/TickCount.h")
    OFH.append("#include \"MsgIntf.h\"\n"); process_exp_stub("common/msg/MsgIntf.h")
    OFH.append("#include \"WaveIntf.h\"\n"); process_exp_stub("common/sound/WaveIntf.h")
    OFH.append("#ifdef __WINVER__\n")
    OFH.append("#include \"WaveImpl.h\"\n")
    OFH.append("#endif\n")
    process_exp_stub("win32/sound/WaveImpl.h")
    OFH.append("#include \"GraphicsLoaderIntf.h\"\n"); process_exp_stub("common/visual/GraphicsLoaderIntf.h")
    OFH.append("#include \"tvpfontstruc.h\"\n"); process_exp_stub("common/visual/tvpfontstruc.h")
    OFH.append("#include \"FontServiceIntf.h\"\n"); process_exp_stub("common/visual/FontServiceIntf.h")
    OFH.append("#include \"tvpinputdefs.h\"\n"); process_exp_stub("common/visual/tvpinputdefs.h")
    OFH.append("#include \"LayerBitmapIntf.h\"\n"); process_exp_stub("common/visual/LayerBitmapIntf.h")
    OFH.append("#include \"drawable.h\"\n"); process_exp_stub("common/visual/drawable.h")
    OFH.append("#include \"ComplexRect.h\"\n"); process_exp_stub("common/visual/ComplexRect.h")
    OFH.append("#include \"LayerIntf.h\"\n"); process_exp_stub("common/visual/LayerIntf.h")
    OFH.append("#include \"LayerManager.h\"\n"); process_exp_stub("common/visual/LayerManager.h")
    OFH.append("#include \"WindowIntf.h\"\n"); process_exp_stub("common/visual/WindowIntf.h")
    OFH.append("#include \"WindowImpl.h\"\n")
    process_exp_stub("win32/visual/WindowImpl.h")
    process_exp_stub("generic/visual/WindowImpl.h")
    OFH.append("#include \"ViewportConfig.h\"\n"); process_exp_stub("common/visual/ViewportConfig.h")
    OFH.append("#include \"ViewportBackground.h\"\n"); process_exp_stub("common/visual/ViewportBackground.h")
    OFH.append("#include \"DrawDevice.h\"\n"); process_exp_stub("common/visual/DrawDevice.h")
    OFH.append("#include \"voMode.h\"\n"); process_exp_stub("common/visual/voMode.h")
    OFH.append("#include \"VideoOvlIntf.h\"\n"); process_exp_stub("common/visual/VideoOvlIntf.h")
    OFH.append("#ifdef __WINVER__\n")
    OFH.append("#include \"VideoPresenter.h\"\n")
    OFH.append("#endif\n")
    process_exp_stub("win32/visual/VideoPresenter.h")
    OFH.append("#include \"elements/DialogRenderer.h\"\n"); process_exp_stub("common/visual/elements/DialogRenderer.h")
    OFH.append("#include \"TransIntf.h\"\n"); process_exp_stub("common/visual/TransIntf.h")
    OFH.append("#include \"transhandler.h\"\n"); process_exp_stub("common/visual/transhandler.h")
    OFH.append("#include \"tvpgl.h\"\n"); process_exp_stub("common/visual/tvpgl.h")
    OFH.append("#include \"OpenGLHeader.h\"\n"); process_exp_stub("common/visual/opengl/OpenGLHeader.h")

    defs_misc = defs
    defs = ''

    all_list = method_list + func_list

    OFH.append("\n#include <zlib.h>\n")

    # func_data: pair[1] (func_exp_name) + NUL, for each all_list entry
    func_data_str = ''
    for each in all_list:
        pair = each.split('\t')
        func_data_str += pair[1] + "\0"
    func_data = func_data_str.encode('latin-1')

    deflateout = zlib.compress(func_data, 6)

    # emit: each byte -> "0x%02x, ", wrap to 96-char lines, trailing "\n"
    emit = ''.join("0x%02x, " % b for b in deflateout)
    wrapped = []
    i = 0
    n = len(emit)
    while i + 96 <= n:
        wrapped.append(emit[i:i + 96])
        wrapped.append('\n')
        i += 96
    wrapped.append(emit[i:])
    emitdata = ''.join(wrapped) + '\n'

    OFH.append("/* function table is pretty large; is compressed via zlib */\n"
               "static tjs_uint8 compressed_functable[] = {\n" +
               emitdata +
               "\n};\n"
               "static void * func_ptrs[] = {\n")

    icount = 0
    for each in all_list:
        pair = each.split('\t')
        OFH.append("\t")
        OFH.append("(void*)" + pair[0] + ",")
        OFH.append("\n")
        icount += 1

    OFH.append("\n};\n\n")

    OFH.append("\nvoid TVPExportFunctions()\n{\n")
    OFH.append("\tconst unsigned long compressed_size = " + str(len(deflateout)) + ";\n")
    OFH.append("\tconst unsigned long decompressed_size = " + str(len(func_data)) + ";\n")
    OFH.append("\tconst tjs_int function_count = " + str(icount) + ";\n")
    OFH.append(
        "\tunsigned char * dest = new unsigned char [decompressed_size];\n"
        "\n"
        "\ttry\n"
        "\t{\n"
        "\t\tunsigned long dest_size = decompressed_size;\n"
        "\n"
        "\t\tint result = uncompress(dest, &dest_size,\n"
        "\t\t\t(unsigned char*)compressed_functable, compressed_size);\n"
        "\t\tif(result != Z_OK || dest_size != decompressed_size) { TVPThrowInternalError; }\n"
        "\n"
        "\t\tconst unsigned char *p = dest;\n"
        "\n"
        "\t\tfor(tjs_int i = 0; i < function_count; i++)\n"
        "\t\t{\n"
        "\t\t\tTVPAddExportFunction((const char *)p, ((void **)func_ptrs)[i]);\n"
        "\t\t\twhile(*p) p++;\n"
        "\t\t\tp++;\n"
        "\t\t}\n"
        "\t}\n"
        "\tcatch(...)\n"
        "\t{\n"
        "\t\tdelete [] dest;\n"
        "\t\tthrow;\n"
        "\t}\n"
        "\tdelete [] dest;\n"
        "}\n")

    # ======================================================================
    #  tp_stub.h / tp_stub.cpp
    # ======================================================================
    OCFH.append(copyright)
    OHFH.append(copyright)

    OCFH.append(
        "\n"
        "#include \"tp_stub.h\"\n"
        "\n"
        "namespace krkrz_plugin {\n"
        "\n"
        "#define TVP_IN_PLUGIN_STUB\n"
        "\n"
        "tjs_int TVPPluginGlobalRefCount = 0;\n"
        "\n"
        "//---------------------------------------------------------------------------\n"
        "// stubs\n"
        "//---------------------------------------------------------------------------\n")

    OHFH.append(
        "#ifndef __TP_STUB_H__\n"
        "#define __TP_STUB_H__\n"
        "\n"
        "#ifndef __cplusplus\n"
        "\t#error Sorry, currently tp_stub.h can only be used in C++ mode.\n"
        "#endif\n"
        "\n"
        "#ifdef _WIN32\n"
        "#define _CRT_SECURE_NO_WARNINGS 1\n"
        "#define WIN32_LEAN_AND_MEAN\n"
        "#define NOMINMAX \n"
        "#include <windows.h>\n"
        "#include <objidl.h> // for IStream\n"
        "#define STDCALL __stdcall\n"
        "#else\n"
        "#define STDCALL\n"
        "typedef void* HWND;\n"
        "#endif\n"
        "\n"
        "#ifdef __GENERIC__\n"
        "#include <functional>\n"
        "#else\n"
        "#define __WINVER__\n"
        "#endif\n"
        "\n"
        "// for compatibillyty with old plugins\n"
        "#ifndef DIRECT3D_VERSION\n"
        "struct IDirect3D9;\n"
        "#endif\n"
        "\n" +
        # Japanese comment carried verbatim as UTF-8 bytes (stored as latin-1)
        ("// Track V-E: overlay presenter が使う D3D11 型 "
         "(前方宣言のみ・d3d11.h は持ち込まない)\n"
         ).encode('utf-8').decode('latin-1') +
        "#ifndef __d3d11_h__\n"
        "struct ID3D11Device;\n"
        "struct ID3D11DeviceContext;\n"
        "struct ID3D11RenderTargetView;\n"
        "#endif\n"
        "\n"
        "#include <string>\n"
        "#include <stdarg.h>\n"
        "#include <stdint.h>\n"
        "#include <climits>\n"
        "\n"
        "namespace krkrz_plugin {\n"
        "\n")

    OHFH.append(defs_system)

    OHFH.append(
        "\n"
        "#ifdef __BORLANDC__\n"
        "#pragma warn -8027\n"
        "#endif\n"
        "\n"
        "//---------------------------------------------------------------------------\n"
        "// function import pointers\n"
        "//---------------------------------------------------------------------------\n"
        "\n"
        "extern void * TVPGetImportFuncPtr(const char *name);\n"
        "\n"
        "\n")

    for each in all_list:
        pair = each.split('\t')
        OHFH.append("extern void * TVPImportFuncPtr" + pair[5] + ";\n")

    OHFH.append(
        "\n"
        "\n"
        "//---------------------------------------------------------------------------\n"
        "// tTJSVariantString\n"
        "//---------------------------------------------------------------------------\n"
        "\n")

    content = read_file("common/tjs2/tjsVariantString.h")
    OHFH.append(
        "class tTJSVariantString : protected tTJSVariantString_S\n"
        "{\n"
        "\t// do not create an instance of this class directly.\n"
        "\n"
        "public:\n")
    for each in variantstring:
        OHFH.append(each + "\n")
    m = re.search(r'/\*start-of-tTJSVariantString\*/(.*?)/\*end-of-tTJSVariantString\*/', content, flags=FLAGS)
    cls = m.group(1)
    for mm in re.finditer(r'/\*m\[\*/(.*?)/\*\]m\*/', cls, flags=FLAGS):
        OHFH.append("\t")
        OHFH.append(mm.group(1))
        OHFH.append("\n\n")
    OHFH.append("};\n")

    OHFH.append(
        "//---------------------------------------------------------------------------\n"
        "// tTJSVariantOctet\n"
        "//---------------------------------------------------------------------------\n"
        "\n")
    content = read_file("common/tjs2/tjsVariant.h")
    OHFH.append(
        "class tTJSVariantOctet : protected tTJSVariantOctet_S\n"
        "{\n"
        "\t// do not create an instance of this class directly.\n"
        "\n"
        "public:\n")
    for each in variantoctet:
        OHFH.append(each + "\n")
    m = re.search(r'/\*start-of-tTJSVariantOctet\*/(.*?)/\*end-of-tTJSVariantOctet\*/', content, flags=FLAGS)
    cls = m.group(1)
    for mm in re.finditer(r'/\*m\[\*/(.*?)/\*\]m\*/', cls, flags=FLAGS):
        OHFH.append("\t")
        OHFH.append(mm.group(1))
        OHFH.append("\n\n")
    OHFH.append("};\n")

    OHFH.append(
        "//---------------------------------------------------------------------------\n"
        "// tTJSVariant\n"
        "//---------------------------------------------------------------------------\n"
        "\n")
    content = read_file("common/tjs2/tjsVariant.h")
    OHFH.append(
        "class tTJSVariant : protected tTJSVariant_S\n"
        "{\n"
        "\n"
        "public:\n")
    for each in variant:
        OHFH.append(each + "\n")
    m = re.search(r'/\*start-of-tTJSVariant\*/(.*?)/\*end-of-tTJSVariant\*/', content, flags=FLAGS)
    cls = m.group(1)
    for mm in re.finditer(r'/\*m\[\*/(.*?)/\*\]m\*/', cls, flags=FLAGS):
        OHFH.append("\t")
        OHFH.append(mm.group(1))
        OHFH.append("\n\n")
    OHFH.append("};\n")

    OHFH.append(
        "//---------------------------------------------------------------------------\n"
        "// tTJSString\n"
        "//---------------------------------------------------------------------------\n"
        "\n")
    content = read_file("common/tjs2/tjsString.h")
    OHFH.append(
        "class tTJSString : protected tTJSString_S\n"
        "{\n"
        "\n"
        "public:\n")
    for each in string:
        OHFH.append(each + "\n")
    m = re.search(r'/\*start-of-tTJSString\*/(.*?)/\*end-of-tTJSString\*/', content, flags=FLAGS)
    cls = m.group(1)
    for mm in re.finditer(r'/\*m\[\*/(.*?)/\*\]m\*/', cls, flags=FLAGS):
        OHFH.append("\t")
        OHFH.append(mm.group(1))
        OHFH.append("\n\n")
    OHFH.append("};\n")

    OHFH.append(
        "\n"
        "//---------------------------------------------------------------------------\n"
        "// stubs (misc)\n"
        "//---------------------------------------------------------------------------\n"
        "\n")
    OHFH.append(defs_misc)

    OHFH.append(
        "//---------------------------------------------------------------------------\n"
        "\n"
        "\n"
        "\n"
        "\n"
        "//---------------------------------------------------------------------------\n"
        "// stubs\n"
        "//---------------------------------------------------------------------------\n"
        "\n")

    for each in func_list:
        pair = each.split('\t')
        envname = pair[9] if len(pair) > 9 else None
        if envname:
            OHFH.append("#ifdef " + envname + "\n")
        OHFH.append("inline " + pair[3] + "\n")
        OHFH.append("{\n")
        OHFH.append(
            "\tif(!TVPImportFuncPtr" + pair[5] + ")\n"
            "\t{\n"
            "\t\tstatic char funcname[] = \"" + pair[1] + "\";\n"
            "\t\tTVPImportFuncPtr" + pair[5] + " = TVPGetImportFuncPtr(funcname);\n"
            "\t}\n")
        OHFH.append("\ttypedef " + pair[7] + ";\n")
        OHFH.append("\t" + ('' if pair[8] == 'void' else 'return ') +
                    "((__functype)(TVPImportFuncPtr" + pair[5] + "))")
        OHFH.append("(" + pair[6] + ");\n")
        OHFH.append("}\n")
        if envname:
            OHFH.append("#endif\n")

    OCFH.append(
        "//---------------------------------------------------------------------------\n"
        "// Stub library setup\n"
        "//---------------------------------------------------------------------------\n"
        "\n"
        "static iTVPFunctionExporter * TVPFunctionExporter = NULL;\n"
        "\n"
        "void * TVPGetImportFuncPtr(const char *name)\n"
        "{\n"
        "\tvoid *ptr;\n"
        "\tif(TVPFunctionExporter->QueryFunctionsByNarrowString(&name, &ptr, 1))\n"
        "\t{\n"
        "\t\t// succeeded\n"
        "\t}\n"
        "\telse\n"
        "\t{\n"
        "\t\t// failed\n"
        "\t\tstatic const char *funcname = \"void ::TVPThrowPluginUnboundFunctionError(const char *)\";\n"
        "\t\tif(!TVPFunctionExporter->QueryFunctionsByNarrowString(&funcname, &ptr, 1))\n"
        "\t\t{\n"
        "\t\t\t*(int*)0 = 0; // causes an error\n"
        "\t\t}\n"
        "\t\ttypedef void (STDCALL * __functype)(const char *);\n"
        "\t\t((__functype)(ptr))(name);\n"
        "\t}\n"
        "\treturn ptr;\n"
        "}\n"
        "\n"
        "/* TVPInitImportStub : stub initialization */\n"
        "bool TVPInitImportStub(iTVPFunctionExporter * exporter)\n"
        "{\n"
        "\t// set TVPFunctionExporter\n"
        "\tTVPFunctionExporter = exporter;\n"
        "\treturn true;\n"
        "}\n"
        "\n"
        "/* TVPUninitImportStub : stub uninitialization */\n"
        "void TVPUninitImportStub()\n"
        "{\n"
        "}\n"
        "\n"
        "\n"
        "\n")

    for each in all_list:
        pair = each.split('\t')
        OCFH.append("void * TVPImportFuncPtr" + pair[5] + " = NULL;\n")

    OCFH.append(impls)

    OHFH.append(
        "\n"
        "#ifdef __BORLANDC__\n"
        "#pragma warn .8027\n"
        "#endif\n"
        "\n"
        "//---------------------------------------------------------------------------\n"
        "// Stub library setup\n"
        "//---------------------------------------------------------------------------\n"
        "extern bool TVPInitImportStub(iTVPFunctionExporter * exporter);\n"
        "extern void TVPUninitImportStub();\n"
        "//---------------------------------------------------------------------------\n"
        "\n"
        "//---------------------------------------------------------------------------\n"
        "// Global reference count\n"
        "//---------------------------------------------------------------------------\n"
        "extern tjs_int TVPPluginGlobalRefCount;\n"
        "//---------------------------------------------------------------------------\n"
        "\n")

    # ---- exception protected function stub (iTJSDispatch2) -----------------
    oh = ''.join(OHFH)
    m = re.search(r'class\s+iTJSDispatch2\s+\{(.*?)\}', oh, flags=FLAGS)
    if not m:
        raise SystemExit("iTJSDispatch2 not found")
    cls = m.group(1)
    cls = re.sub(r'//.*?\n', '', cls, flags=FLAGS)
    cls = re.sub(r'/\*.*?\*/', '', cls, flags=FLAGS)

    hc = ''
    cc = ''
    cc += (
        "\n"
        "static bool TJS_USERENTRY _CatchFuncCall(void *data, const tTVPExceptionDesc & desc)\n"
        "{\n"
        "\tthrow desc;\n"
        "}\n")

    for m in re.finditer(r'virtual\s+(\w+)\s+TJS_INTF_METHOD\s+(\w+)\s*\(\s*(.*?)\s*\)', cls, flags=FLAGS):
        ret_type = m.group(1)
        method_name = m.group(2)
        raw = m.group(3)
        args = _perl_split_re(r'\s*,\s*', '' if raw == 'void' else raw)

        hc += ("extern " + ret_type + " Try_iTJSDispatch2_" + method_name + "(" +
               ', '.join(["iTJSDispatch2 * _this"] + args) + ");\n")

        cc += "struct t_iTJSDispatch2_" + method_name + "\n"
        cc += "{\n"
        if ret_type != 'void':
            cc += "\t" + ret_type + " _ret;\n"

        for a in ["iTJSDispatch2 * _this"] + args:
            cc += "\t" + a + ";\n"

        arg_names = []
        for a in args:
            mm = re.search(r'(\w+)$', a, flags=re.ASCII)
            if mm:
                arg_names.append(mm.group(1))

        cc += "\tt_iTJSDispatch2_" + method_name + "(\n\t\t\t"
        cc += "_,\n\t\t\t".join(["iTJSDispatch2 * _this"] + args)
        cc += "_\n\t\t\t) :\n\t\t"
        arg_initials = []
        for an in ["_this"] + arg_names:
            arg_initials.append(an + "(" + an + "_)")
        cc += ",\n\t\t".join(arg_initials)
        cc += "\t{;}\n"
        cc += "\n};\n"

        cc += "static void TJS_USERENTRY _Try_iTJSDispatch2_" + method_name + "(void *data)\n"
        cc += "{\n"
        cc += "\tt_iTJSDispatch2_" + method_name + " * arg = (t_iTJSDispatch2_" + method_name + " *)data;\n"
        # Perl bug: $ret_Type (capital T) is undef -> always true.
        cc += "\targ->_ret = \n"
        cc += "\targ->_this->" + method_name + "(\n\t\t"
        arg_args = []
        for an in arg_names:
            arg_args.append("arg->" + an)
        cc += ",\n\t\t".join(arg_args)
        cc += "\n\t\t);\n"
        cc += "}\n"
        cc += (ret_type + " Try_iTJSDispatch2_" + method_name + "(" +
               ', '.join(["iTJSDispatch2 * _this"] + args) + ")\n")
        cc += "{\n"
        cc += "\tt_iTJSDispatch2_" + method_name + " arg(\n\t\t"
        cc += ",\n\t\t".join(["_this"] + arg_names)
        cc += "\n\t);\n"
        cc += "\tTVPDoTryBlock(_Try_iTJSDispatch2_" + method_name + ", _CatchFuncCall, NULL, &arg);\n"
        # Perl bug: $ret_Type undef -> always true.
        cc += "\treturn arg._ret;\n"
        cc += "}\n"

    OHFH.append(
        "//---------------------------------------------------------------------------\n"
        "// exception protected function stub\n"
        "//---------------------------------------------------------------------------\n"
        "\n")
    OHFH.append(hc)
    OHFH.append(
        "\n"
        "} // namespace\n"
        "\n"
        "using namespace krkrz_plugin;\n"
        "\n"
        "#endif\n")

    OCFH.append(
        "//---------------------------------------------------------------------------\n"
        "// exception protected function stub\n"
        "//---------------------------------------------------------------------------\n"
        "\n")
    OCFH.append(cc)
    OCFH.append(
        "\n"
        "} // namespace\n")

    # ---- write outputs -----------------------------------------------------
    write_file("common/base/FuncStubs.h", ''.join(fh_h))
    write_file("common/base/FuncStubs.cpp", ''.join(OFH))
    write_file("tp_stub/tp_stub.h", ''.join(OHFH))
    write_file("tp_stub/tp_stub.cpp", ''.join(OCFH))


if __name__ == '__main__':
    main()
