#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ライセンステキスト圧縮収録ソース生成器

manifest.json に列挙したライセンス文 (フィールドは doc/LicenseSystem.md 参照) を
zlib deflate で圧縮し、C++ ソースへ埋め込む。3 モード:

  本体内蔵テーブル (既定):
    python licenses/gen_licenses_c.py
      → common/base/BuiltinLicenses.cpp (tTVPBuiltinLicenseEntry 配列)

  プラグイン用登録関数:
    python <core>/licenses/gen_licenses_c.py --mode plugin \
        --manifest <plugin>/licenses/manifest.json \
        --out <plugin>/LicensesGen.cpp --func RegisterMyPluginLicenses
      → tp_stub の TVPRegisterLicense を呼ぶ関数を生成。プラグインの
        リンク時コールバック (NCB_PRE_REGIST_CALLBACK 等) から呼ぶ。

  本体内モジュール用登録関数:
    python licenses/gen_licenses_c.py --mode module \
        --manifest <module>/licenses/manifest.json \
        --out <module>/LicensesGen.cpp --func RegisterXxxLicenses
      → 本体に静的リンクされるが manifest を分けたいモジュール向け。
        tp_stub ではなく LicenseIntf.h を直接使う (互換ガード無し)。

  一覧表 (Markdown):
    python licenses/gen_licenses_c.py --mode table \
        --plugins <umbrella>/src/plugins \
        --out <umbrella>/doc/guide/BundledLicenses.md
      → 本体 / プラグイン / その他 (フォント) に分けた対応表を生成。
        種別は manifest の "license" フィールドをそのまま使う (推測しない)。

manifest のエントリに "when": "MACRO" を付けると、そのエントリ (バイト配列と
テーブル行/登録呼び出し) が #if defined(MACRO) で囲まれる。ビルド構成で
実際にはリンクされないコンポーネント (例: ThorVG の Lottie ローダを切ると
JerryScript / RapidJSON は 1 行もコンパイルされない) を、一覧へ載せない
ために使う。マクロは CMake 側の構成判定から定義する。

出力はバイト一致なら書き換えない (mtime 保護)。テキストは UTF-8 として
収録される (収録元が UTF-8/ASCII であること)。
"""
import argparse, json, os, sys, zlib


def load_manifest(path):
    with open(path, encoding="utf-8") as f:
        doc = json.load(f)
    base = os.path.dirname(os.path.abspath(path))
    entries = []
    for e in doc["entries"]:
        fp = os.path.join(base, e["file"])
        with open(fp, "rb") as f:
            data = f.read()
        # 収録テキストは UTF-8 (BOM は剥がす)。CRLF は LF へ正規化
        if data.startswith(b"\xef\xbb\xbf"):
            data = data[3:]
        data = data.replace(b"\r\n", b"\n")
        entries.append((e["name"], e.get("group", ""), data, e.get("when") or None))
    return entries


def emit_bytes(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 24):
        lines.append("\t" + "".join(f"{b}," for b in data[i:i + 24]))
    lines.append("};")
    return "\n".join(lines)


def cstr(s):
    # ASCII 前提の表示名 (非 ASCII は \uXXXX でエスケープ)
    out = []
    for ch in s:
        o = ord(ch)
        if ch in '"\\':
            out.append("\\" + ch)
        elif 0x20 <= o < 0x7f:
            out.append(ch)
        else:
            out.append(f"\\u{o:04x}" if o <= 0xffff else f"\\U{o:08x}")
    return '"' + "".join(out) + '"'


def generate(entries, mode, func):
    out = []
    out.append("/* generated by licenses/gen_licenses_c.py — 手編集禁止。")
    out.append("   licenses/manifest.json + licenses/texts/ を編集して再生成する。 */")
    out.append("")
    if mode in ("core", "module"):
        out.append('#include "tjsCommHead.h"')
        out.append('#include "LicenseIntf.h"')
    else:
        out.append('#include "tp_stub.h"')
        out.append("")
        out.append("/* License API 非対応バージョンの tp_stub / 本体ヘッダと組み合わせた")
        out.append("   ビルドでは登録をまるごとスキップして空関数になる (互換ガード)。 */")
        out.append("#ifdef TVP_HAS_LICENSE_API")
    out.append("")
    arrays = []
    table = []
    for i, (name, group, data, when) in enumerate(entries):
        comp = zlib.compress(data, 9)
        sym = f"lic_{i:02d}"
        arrays.append(f"/* {name} ({len(data)} -> {len(comp)} bytes) */")
        if when:
            arrays.append(f"#if defined({when})")
        arrays.append(emit_bytes(sym, comp))
        if when:
            arrays.append("#endif")
        table.append((name, group, sym, len(comp), len(data), when))
    out.extend(arrays)
    out.append("")
    if mode == "core":
        out.append("const tTVPBuiltinLicenseEntry TVPBuiltinLicenses[] = {")
        for name, group, sym, csz, osz, when in table:
            if when:
                out.append(f"#if defined({when})")
            out.append(f"\t{{ TJS_W({cstr(name)}), TJS_W({cstr(group)}), {sym}, {csz}, {osz} }},")
            if when:
                out.append("#endif")
        out.append("};")
        # 条件付きエントリがあるので件数は配列サイズから求める (手書き定数にしない)
        out.append("const int TVPBuiltinLicenseCount =")
        out.append("\tsizeof(TVPBuiltinLicenses) / sizeof(TVPBuiltinLicenses[0]);")
    else:
        out.append(f"void {func}()")
        out.append("{")
        for name, group, sym, csz, osz, when in table:
            if when:
                out.append(f"#if defined({when})")
            out.append(f"\tTVPRegisterLicense(TJS_W({cstr(name)}), TJS_W({cstr(group)}), {sym}, {csz}, {osz});")
            if when:
                out.append("#endif")
        out.append("}")
        if mode == "plugin":
            out.append("")
            out.append("#else /* !TVP_HAS_LICENSE_API */")
            out.append("")
            out.append(f"void {func}() {{}}")
            out.append("")
            out.append("#endif /* TVP_HAS_LICENSE_API */")
    out.append("")
    return "\n".join(out)


GROUP_LABEL = {
    "engine":      "エンジン基盤",
    "font-engine": "文字組み (glyphware)",
    "audio":       "音声",
    "video":       "動画",
    "ui":          "UI (Elements)",
    "platform":    "プラットフォーム",
    "font":        "フォント",
}


def load_meta(path):
    """ライセンス本文は読まずにメタデータだけ取り出す (表生成用)。"""
    with open(path, encoding="utf-8") as f:
        doc = json.load(f)
    out = []
    for e in doc["entries"]:
        if not e.get("license"):
            raise SystemExit(f'"license" が無いエントリ: {e["name"]} ({path})')
        out.append(e)
    return out


def md_escape(s):
    return s.replace("|", "\\|")


def remark(e):
    """備考欄。 構成依存なら条件を頭に出す。"""
    parts = []
    if e.get("when"):
        parts.append(f'**`{e["when"]}` 有効時のみ**')
    if e.get("note"):
        parts.append(e["note"])
    return " / ".join(md_escape(p) for p in parts)


def generate_table(core_manifest, plugins_dir):
    core = load_meta(core_manifest)
    body = [e for e in core if e.get("group") != "font"]
    fonts = [e for e in core if e.get("group") == "font"]

    plugs = []
    if plugins_dir and os.path.isdir(plugins_dir):
        for d in sorted(os.listdir(plugins_dir)):
            mf = os.path.join(plugins_dir, d, "licenses", "manifest.json")
            if os.path.isfile(mf):
                for e in load_meta(mf):
                    plugs.append((d, e))

    cond = sum(1 for e in core if e.get("when")) + sum(1 for _, e in plugs if e.get("when"))

    o = []
    o.append("# 同梱ライセンス一覧")
    o.append("")
    o.append("<!-- generated by src/core/licenses/gen_licenses_c.py --mode table — 手編集禁止。")
    o.append("     各 licenses/manifest.json を編集して再生成する。 -->")
    o.append("")
    o.append(f"配布物に載る第三者コンポーネントの対応表です。本体 {len(body)} 件 / "
             f"プラグイン {len(plugs)} 件 / フォント {len(fonts)} 件 "
             f"(うち構成依存 {cond} 件)。")
    o.append("")
    o.append("正本は各 `licenses/manifest.json`、仕組みの説明は "
             "`src/core/doc/LicenseSystem.md` です。"
             "ライセンス原文は配布物の `licenses/` フォルダに全文が入ります。")
    o.append("")

    o.append("## 本体")
    o.append("")
    o.append("エンジン本体 (exe) に内蔵され、`make install` で `licenses/` へ書き出される分です。")
    o.append("")
    cur = None
    for e in body:
        g = e.get("group", "")
        if g != cur:
            cur = g
            if o[-1] != "":
                o.append("")
            o.append(f"### {GROUP_LABEL.get(g, g)}")
            o.append("")
            o.append("| コンポーネント | ライセンス | 備考 |")
            o.append("|---|---|---|")
        o.append(f'| {md_escape(e["name"])} | {md_escape(e["license"])} | {remark(e)} |')
    o.append("")

    o.append("## プラグイン")
    o.append("")
    o.append("各プラグインの DLL 側が実行時に登録します "
             "(`System.getLicenseList()` / `-license` に合流)。"
             "原文は install 時に配布物の `licenses/plugins/` へも書き出されます "
             "(実際にビルドしたプラグインのぶんだけ)。")
    o.append("")
    if plugs:
        o.append("| プラグイン | コンポーネント | ライセンス | 備考 |")
        o.append("|---|---|---|---|")
        for d, e in plugs:
            o.append(f'| {md_escape(d)} | {md_escape(e["name"])} | '
                     f'{md_escape(e["license"])} | {remark(e)} |')
    else:
        o.append("(プラグインの manifest が見つかりませんでした)")
    o.append("")

    o.append("## その他 (フォント・データ)")
    o.append("")
    o.append("コードではなくデータですが、配布物に載る以上は同じ一覧で扱います。"
             "案件が独自フォントを足す場合は manifest ではなく "
             "**ゲームデータ側の `licenses/*.txt`** に置けば実行時に合流します。")
    o.append("")
    o.append("| コンポーネント | ライセンス | 備考 |")
    o.append("|---|---|---|")
    for e in fonts:
        o.append(f'| {md_escape(e["name"])} | {md_escape(e["license"])} | {remark(e)} |')
    o.append("| 案件が置く分 | 案件ごと | `<データ>/licenses/*.txt` を実行時に列挙 |")
    o.append("")

    conds = [e for e in core if e.get("when")] + [e for _, e in plugs if e.get("when")]
    if conds:
        o.append("## 構成依存のエントリ")
        o.append("")
        o.append("ビルド構成によっては 1 行もコンパイルされないコンポーネントです。"
                 "マクロが定義されない構成では内蔵テーブルにも配布物にも出ません。")
        o.append("")
        o.append("| マクロ | 対象 |")
        o.append("|---|---|")
        by_macro = {}
        for e in conds:
            by_macro.setdefault(e["when"], []).append(e["name"])
        for macro, names in sorted(by_macro.items()):
            uniq = sorted(set(names))
            o.append(f'| `{macro}` | {" / ".join(md_escape(n) for n in uniq)} |')
        o.append("")

    return "\n".join(o)


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["core", "plugin", "module", "table"], default="core")
    ap.add_argument("--manifest", default=os.path.join(script_dir, "manifest.json"))
    ap.add_argument("--out", default=os.path.join(script_dir, "..", "common", "base", "BuiltinLicenses.cpp"))
    ap.add_argument("--func", default="RegisterPluginLicenses")
    ap.add_argument("--plugins", default=None,
                    help="table モード: プラグイン群のフォルダ (<name>/licenses/manifest.json を走査)")
    a = ap.parse_args()

    if a.mode == "table":
        if a.out == ap.get_default("out"):
            ap.error("--mode table では --out を指定してください")
        text = generate_table(a.manifest, a.plugins)
        count = len(load_meta(a.manifest))
        summary = f"{count} entries + plugins"
    else:
        entries = load_manifest(a.manifest)
        text = generate(entries, a.mode, a.func)
        total_o = sum(len(d) for _, _, d, _w in entries)
        summary = f"{len(entries)} entries, {total_o} bytes original"

    data = text.encode("utf-8")
    out = os.path.abspath(a.out)
    try:
        with open(out, "rb") as f:
            if f.read() == data:
                print("unchanged", out)
                return
    except FileNotFoundError:
        pass
    with open(out, "wb") as f:
        f.write(data)
    print(f"wrote {out} ({summary})")


if __name__ == "__main__":
    main()
