#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ライセンステキスト圧縮収録ソース生成器

manifest.json (name/group/file) に列挙したライセンス文を zlib deflate で
圧縮し、C++ ソースへ埋め込む。2 モード:

  本体内蔵テーブル (既定):
    python licenses/gen_licenses_c.py
      → common/base/BuiltinLicenses.cpp (tTVPBuiltinLicenseEntry 配列)

  プラグイン用登録関数:
    python <core>/licenses/gen_licenses_c.py --mode plugin \
        --manifest <plugin>/licenses/manifest.json \
        --out <plugin>/LicensesGen.cpp --func RegisterMyPluginLicenses
      → tp_stub の TVPRegisterLicense を呼ぶ関数を生成。プラグインの
        リンク時コールバック (NCB_PRE_REGIST_CALLBACK 等) から呼ぶ。

出力はバイト一致なら書き換えない (mtime 保護)。テキストは UTF-8 として
収録される (収録元が UTF-8/ASCII であること)。
"""
import argparse, json, os, sys, zlib


def load_manifest(path):
    with open(path, encoding="utf-8") as f:
        doc = json.load(f)
    base = os.path.dirname(os.path.abspath(path))
    entries = []
    for e in doc["entries"]:
        fp = os.path.join(base, e["file"])
        with open(fp, "rb") as f:
            data = f.read()
        # 収録テキストは UTF-8 (BOM は剥がす)。CRLF は LF へ正規化
        if data.startswith(b"\xef\xbb\xbf"):
            data = data[3:]
        data = data.replace(b"\r\n", b"\n")
        entries.append((e["name"], e.get("group", ""), data))
    return entries


def emit_bytes(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 24):
        lines.append("\t" + "".join(f"{b}," for b in data[i:i + 24]))
    lines.append("};")
    return "\n".join(lines)


def cstr(s):
    # ASCII 前提の表示名 (非 ASCII は \uXXXX でエスケープ)
    out = []
    for ch in s:
        o = ord(ch)
        if ch in '"\\':
            out.append("\\" + ch)
        elif 0x20 <= o < 0x7f:
            out.append(ch)
        else:
            out.append(f"\\u{o:04x}" if o <= 0xffff else f"\\U{o:08x}")
    return '"' + "".join(out) + '"'


def generate(entries, mode, func):
    out = []
    out.append("/* generated by licenses/gen_licenses_c.py — 手編集禁止。")
    out.append("   licenses/manifest.json + licenses/texts/ を編集して再生成する。 */")
    out.append("")
    if mode == "core":
        out.append('#include "tjsCommHead.h"')
        out.append('#include "LicenseIntf.h"')
    else:
        out.append('#include "tp_stub.h"')
        out.append("")
        out.append("/* License API 非対応バージョンの tp_stub / 本体ヘッダと組み合わせた")
        out.append("   ビルドでは登録をまるごとスキップして空関数になる (互換ガード)。 */")
        out.append("#ifdef TVP_HAS_LICENSE_API")
    out.append("")
    arrays = []
    table = []
    for i, (name, group, data) in enumerate(entries):
        comp = zlib.compress(data, 9)
        sym = f"lic_{i:02d}"
        arrays.append(f"/* {name} ({len(data)} -> {len(comp)} bytes) */")
        arrays.append(emit_bytes(sym, comp))
        table.append((name, group, sym, len(comp), len(data)))
    out.extend(arrays)
    out.append("")
    if mode == "core":
        out.append("const tTVPBuiltinLicenseEntry TVPBuiltinLicenses[] = {")
        for name, group, sym, csz, osz in table:
            out.append(f"\t{{ TJS_W({cstr(name)}), TJS_W({cstr(group)}), {sym}, {csz}, {osz} }},")
        out.append("};")
        out.append(f"const int TVPBuiltinLicenseCount = {len(table)};")
    else:
        out.append(f"void {func}()")
        out.append("{")
        for name, group, sym, csz, osz in table:
            out.append(f"\tTVPRegisterLicense(TJS_W({cstr(name)}), TJS_W({cstr(group)}), {sym}, {csz}, {osz});")
        out.append("}")
        out.append("")
        out.append("#else /* !TVP_HAS_LICENSE_API */")
        out.append("")
        out.append(f"void {func}() {{}}")
        out.append("")
        out.append("#endif /* TVP_HAS_LICENSE_API */")
    out.append("")
    return "\n".join(out)


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["core", "plugin"], default="core")
    ap.add_argument("--manifest", default=os.path.join(script_dir, "manifest.json"))
    ap.add_argument("--out", default=os.path.join(script_dir, "..", "common", "base", "BuiltinLicenses.cpp"))
    ap.add_argument("--func", default="RegisterPluginLicenses")
    a = ap.parse_args()

    entries = load_manifest(a.manifest)
    text = generate(entries, a.mode, a.func)
    data = text.encode("utf-8")
    out = os.path.abspath(a.out)
    try:
        with open(out, "rb") as f:
            if f.read() == data:
                print("unchanged", out)
                return
    except FileNotFoundError:
        pass
    with open(out, "wb") as f:
        f.write(data)
    total_o = sum(len(d) for _, _, d in entries)
    print(f"wrote {out} ({len(entries)} entries, {total_o} bytes original)")


if __name__ == "__main__":
    main()
