/*
	this is a part of TVP (KIRIKIRI) software source.
	see other sources for license.
	(C)2001-2009 W.Dee <dee@kikyou.info> and contributors
*/

/* C-language interface to tvpgl_ia32.lib */
/* this file is always generated by summary.pl */

#include "tjsTypes.h"

#include "tvpgl.h"
#include "tvpgl_ia32_intf.h"

/*
 * かつて TLG6 デコード用に NASM 製のアセンブリ実装(*_a / *_mmx_a / *_emmx_a /
 * *_sse_a)を CPU 機能に応じて差し替えていたが、以下の理由で全廃した:
 *  - 32bit 専用で 64bit ビルドでは元から無効化されていた (#ifndef TJS_64BIT_OS)
 *  - 古い nasm でしかコンパイルできず、ツールチェイン依存が重かった
 *  - MMX/EMMX 経路は現代の x86_64 では SSE2 ベースラインに対して実利が無い
 * 現在は tvpgl.c の C リファレンス実装 (*_c) がそのまま使われる。
 * 本関数は呼び出し側の互換のため空 stub として残してある。
 */
void TVPGL_IA32_Init()
{
}

