# バイナリファイルを C 配列ソースへ変換する (objcopy が使えない wasm 向け)
#
# usage:
#   cmake -DINPUT=<file> -DOUTPUT=<file.c> -DSYMBOL=<array symbol> -P Bin2C.cmake
#
# 出力: const char <SYMBOL>[] = { 0x??, ... };
# サイズは呼び出し側 (CMakeLists.txt の EMSCRIPTEN リソース分岐) が
# file(SIZE) で取得してレジストリに焼き込むので、ここでは出力しない。
#
# 注意: 数 MB のファイルに対する string(REGEX REPLACE) は一括だと極端に
# 遅くなるため、チャンクに分割して処理する (チャンク長は hex 2文字 = 1byte
# 境界を跨がないよう偶数にすること)。

if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
    message(FATAL_ERROR "Bin2C.cmake: INPUT / OUTPUT / SYMBOL を指定してください")
endif()

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _len)

set(_body "")
set(_pos 0)
set(_chunk_max 131072) # hex 128K 文字 = 64KB / チャンク (偶数)
while(_pos LESS _len)
    math(EXPR _chunk "${_len} - ${_pos}")
    if(_chunk GREATER ${_chunk_max})
        set(_chunk ${_chunk_max})
    endif()
    string(SUBSTRING "${_hex}" ${_pos} ${_chunk} _part)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _part "${_part}")
    string(APPEND _body "${_part}\n")
    math(EXPR _pos "${_pos} + ${_chunk}")
endwhile()

file(WRITE "${OUTPUT}" "/* Auto-generated by Bin2C.cmake from ${INPUT} */
const char ${SYMBOL}[] = {
${_body}};
")
